# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4f403327674d47c33d2dbbe4b9e4c942bcd7d8aa8abe211e8816f0de0b44babb1df86b5a884939733e865f52be19d1dacdd114b2fdc12167c12fbeef2d0d99

test:
  secret_key_base: 1e7285af22ce79c1922c84a1eb9d0c4668d93dfc974173b1ccef3b12dc8ba5539d979c62afd92bcc0de7a28875ee3a4e3ac49ce541208bcebe2c52016e53d1c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
